version: "3.3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /home/vano/url_shortener_data:/data/db